import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import { User, CreditCode } from '@/lib/models';
import { verifyJwt } from '@/lib/auth';

// GET - Fetch all codes generated by guider
export async function GET(request: NextRequest) {
    try {
        await dbConnect();

        // Get user from token
        const token = request.cookies.get('token')?.value;
        if (!token) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const decoded = verifyJwt(token);
        if (!decoded || !decoded.userId) {
            return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
        }

        const user = await User.findById(decoded.userId);
        if (!user) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        // Check if user is a guider
        if (user.role !== 'guider') {
            return NextResponse.json({ error: 'Only guiders can view credit codes' }, { status: 403 });
        }

        const { searchParams } = new URL(request.url);
        const status = searchParams.get('status');
        const purpose = searchParams.get('purpose');
        const page = parseInt(searchParams.get('page') || '1');
        const limit = parseInt(searchParams.get('limit') || '20');
        const skip = (page - 1) * limit;

        // Build query
        const query: any = { generatedBy: user._id };
        if (status) query.status = status.toUpperCase();
        if (purpose) query.purpose = purpose;

        // Get total count
        const totalCodes = await CreditCode.countDocuments(query);

        // Fetch codes with pagination
        const codes = await CreditCode.find(query)
            .populate('usedBy', 'name username')
            .sort({ createdAt: -1 })
            .skip(skip)
            .limit(limit);

        // Calculate statistics (based on all codes, not paginated)
        const allCodes = await CreditCode.find({ generatedBy: user._id });
        const stats = {
            total: allCodes.length,
            active: allCodes.filter(c => c.status === 'ACTIVE').length,
            used: allCodes.filter(c => c.status === 'USED').length,
            expired: allCodes.filter(c => c.status === 'EXPIRED').length,
            totalValue: allCodes.reduce((sum, c) => sum + c.amount, 0),
            usedValue: allCodes.filter(c => c.status === 'USED').reduce((sum, c) => sum + c.amount, 0),
        };

        return NextResponse.json({
            codes,
            stats,
            totalPages: Math.ceil(totalCodes / limit),
        });

    } catch (error: any) {
        console.error('Error fetching credit codes:', error);
        return NextResponse.json(
            { error: 'Failed to fetch credit codes', details: error.message },
            { status: 500 }
        );
    }
}
